apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
    name: airflow-sa-cluster-admin-binding
subjects:
  - kind: ServiceAccount
    name: airflow-sa
    namespace: airflow
roleRef:
    kind: ClusterRole
    name: cluster-admin
    apiGroup: rbac.authorization.k8s.io