apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: airflowlogs-pvc
spec:
    storageClassName: manual
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 2Gi