apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/log-data/"