apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: webserver-html-pvc
spec:
    storageClassName: manual
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi