apiVersion: v1
kind: Pod
metadata:
  name: nginx-webserver
spec:
  volumes:
    - name: webserver-storage
      persistentVolumeClaim:
        claimName: webserver-html-pvc
  containers:
    - name: nginx-webserver
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: webserver-storage